# Generated by Django 4.2.7 on 2025-03-04 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=50, unique=True, verbose_name='Número de empleado')),
                ('region', models.CharField(choices=[('norte', 'Norte'), ('sur', 'Sur'), ('este', 'Este'), ('oeste', 'Oeste'), ('centro', 'Centro'), ('noroeste', 'Noroeste'), ('noreste', 'Noreste'), ('suroeste', 'Suroeste'), ('sureste', 'Sureste')], default='centro', max_length=20, verbose_name='Región')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
    ]
