# Generated by Django 4.2.7 on 2025-04-04 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_duration_weeks_course_duration_hours'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technician',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='courses.region', verbose_name='Región'),
        ),
    ]
