# Generated by Django 4.2.7 on 2025-04-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_technician_updated_at_alter_technician_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='employee_number',
        ),
        migrations.AddField(
            model_name='technician',
            name='numero_empleado',
            field=models.CharField(default='TEMP', max_length=20, unique=True, verbose_name='Número de empleado'),
        ),
    ]
