# Generated by Django 4.2.7 on 2025-04-04 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_duration_weeks_course_duration_hours'),
        ('users', '0003_convert_employee_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='numero_empleado',
            field=models.CharField(help_text='Este será el nombre de usuario para iniciar sesión', max_length=20, unique=True, verbose_name='Número de empleado'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicians', to='courses.region', verbose_name='Región'),
        ),
    ]
