services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-whirlpool-courses-secretkey-changemeinproduction
      - DATABASE_ENGINE=django.db.backends.mysql
      - DATABASE_NAME=whirlpool_db
      - DATABASE_USER=whirlpool_user
      - DATABASE_PASSWORD=whirlpool_password
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    command: >
      bash -c "sleep 10 &&
               python manage.py migrate &&
               python manage.py collectstatic --noinput &&
               python manage.py runserver 0.0.0.0:8000"

  db:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_DATABASE=whirlpool_db
      - MYSQL_USER=whirlpool_user
      - MYSQL_PASSWORD=whirlpool_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Cambiado a 3307 en el host, manteniendo 3306 en el contenedor

volumes:
  static_volume:
  media_volume:
  mysql_data: