# Generated by Django 4.2.7 on 2025-03-04 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
