# Generated by Django 4.2.7 on 2025-03-13 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desempeno',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desempenos', to='users.technician', verbose_name='Técnico'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='courses.course', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='courseapplication',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to='courses.region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_teaching', to='courses.instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='answer',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.course', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.question', verbose_name='Pregunta'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('course', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='desempeno',
            unique_together={('technician', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='courseapplication',
            unique_together={('course', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'number')},
        ),
    ]
