# Generated by Django 4.2.7 on 2025-04-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_answer_created_at_answer_updated_at_course_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='image',
        ),
        migrations.RemoveField(
            model_name='section',
            name='text',
        ),
        migrations.RemoveField(
            model_name='section',
            name='video_url',
        ),
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, verbose_name='Contenido'),
        ),
    ]
