# Generated by Django 5.1.7 on 2025-04-23 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_question_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='section',
            name='order',
        ),
        migrations.CreateModel(
            name='CourseContentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('section', 'Sección'), ('question', 'Pregunta')], max_length=10)),
                ('content_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_order', to='courses.course')),
            ],
            options={
                'verbose_name': 'Orden de Contenido',
                'verbose_name_plural': 'Orden de Contenidos',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'content_type', 'content_id')},
            },
        ),
    ]
