# Generated by Django 4.2.7 on 2025-04-24 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_question_options_alter_section_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desempeno',
            options={'ordering': ['-fecha'], 'verbose_name': 'Desempeño', 'verbose_name_plural': 'Desempeños'},
        ),
        migrations.AlterUniqueTogether(
            name='desempeno',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='desempeno',
            name='aprobado',
            field=models.BooleanField(default=False, verbose_name='Aprobado'),
        ),
        migrations.AddField(
            model_name='desempeno',
            name='duracion_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Duración Total (minutos)'),
        ),
        migrations.AddField(
            model_name='desempeno',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desempenos_instructor', to='courses.instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='desempeno',
            name='respuestas_incorrectas',
            field=models.PositiveIntegerField(default=0, verbose_name='Respuestas Incorrectas'),
        ),
        migrations.RemoveField(
            model_name='desempeno',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='desempeno',
            name='puntuacion',
        ),
    ]
