# Generated by Django 4.2.7 on 2025-04-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_question_id_alter_section_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, default=50000, primary_key=True, serialize=False),
        ),
    ]
